### ISSUE TITLE
Task execution role required for ECR images

### ISSUE THREAD

**Issue by werkshy** [nathanpeck/aws-cloudformation-fargate#1]
Hi,

I am trying to use an ECR docker image in place of the nginx default, and quickly ran into an awkward error - the service stack failed to create because the task definition needed a role that could access ECR. The exact error that stopped the stack creation was "Fargate requires task definition to have execution role ARN to support ECR images."

I solved this manually by setting up an ecsTaskExecutionRole and then putting the arn into the TaskDefinition like this
```
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ...
      NetworkMode: awsvpc
      ExecutionRoleArn: arn:aws:iam::XXXXX:role/ecsTaskExecutionRole**
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
      ...
```

It might make sense to enable this by default in this reference.
